server:
  port: 8081
  servlet:
    context-path: /task-service

spring:
  application:
    name: task-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:task-service;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
