name: Unit & e2e Test

on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
    branches:
      - 'main'
      - 'release-**'

jobs:
  test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 21
          cache: maven
      - name: Run tests with Maven
        working-directory: ./
        run: mvn -B test --file pom.xml
